export const styles = {
    layout: {
      display: "flex",
      minHeight: "100vh",
      background: "#0F0F13",
      fontFamily: "'Sora', sans-serif",
      color: "#F0EEF8",
    },
    aside: {
      width: "220px",
      background: "#17171E",
      borderRight: "1px solid #2A2A38",
      padding: "24px 16px",
      display: "flex",
      flexDirection: "column",
      gap: "4px",
      flexShrink: 0,
    },
    logo: {
      fontSize: "20px",
      fontWeight: "600",
      color: "#9B8FFF",
      letterSpacing: "-0.5px",
      padding: "0 8px 20px",
      borderBottom: "1px solid #2A2A38",
      marginBottom: "12px",
    },
    logoSpan: {
      color: "#F0EEF8",
    },
    navActive: {
      padding: "10px 12px",
      borderRadius: "10px",
      fontSize: "14px",
      fontWeight: "500",
      cursor: "pointer",
      color: "#9B8FFF",
      background: "#6C63FF22",
      border: "1px solid #6C63FF33",
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    navItem: {
      padding: "10px 12px",
      borderRadius: "10px",
      fontSize: "14px",
      fontWeight: "500",
      cursor: "pointer",
      color: "#888AA8",
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    navDot: {
      width: "7px",
      height: "7px",
      borderRadius: "50%",
      background: "currentColor",
      opacity: 0.6,
      flexShrink: 0,
    },
    main: {
      flex: 1,
      padding: "32px",
      overflow: "auto",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: "32px",
    },
    pageTitle: {
      fontSize: "26px",
      fontWeight: "600",
      letterSpacing: "-0.5px",
    },
    pageSub: {
      fontSize: "13px",
      color: "#888AA8",
      marginTop: "4px",
    },
    btnAdd: {
      background: "#6C63FF",
      color: "#fff",
      border: "none",
      padding: "10px 20px",
      borderRadius: "10px",
      fontSize: "13px",
      fontWeight: "600",
      cursor: "pointer",
      fontFamily: "'Sora', sans-serif",
      letterSpacing: "0.3px",
    },
    stats: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "16px",
      marginBottom: "28px",
    },
    statCard: (accent) => ({
      background: "#17171E",
      border: "1px solid #2A2A38",
      borderRadius: "14px",
      padding: "20px 22px",
      position: "relative",
      overflow: "hidden",
    }),
    statLabel: {
      fontSize: "12px",
      color: "#888AA8",
      fontWeight: "500",
      textTransform: "uppercase",
      letterSpacing: "0.8px",
    },
    statNum: (color) => ({
      fontSize: "34px",
      fontWeight: "600",
      marginTop: "6px",
      letterSpacing: "-1px",
      fontFamily: "'IBM Plex Mono', monospace",
      color,
    }),
    searchBar: {
      background: "#17171E",
      border: "1px solid #2A2A38",
      borderRadius: "10px",
      padding: "10px 16px",
      width: "300px",
      color: "#F0EEF8",
      fontSize: "14px",
      fontFamily: "'Sora', sans-serif",
      outline: "none",
      marginBottom: "20px",
  
  
    },
    tableWrap: {
      background: "#17171E",
      border: "1px solid #2A2A38",
      borderRadius: "16px",
      overflow: "hidden",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
    },
    thead: {
      background: "#1E1E28",
    },
    th: {
      padding: "14px 18px",
      textAlign: "left",
      fontSize: "11px",
      fontWeight: "600",
      color: "#888AA8",
      textTransform: "uppercase",
      letterSpacing: "0.8px",
    },
    thCenter: {
      padding: "14px 18px",
      textAlign: "center",
      fontSize: "11px",
      fontWeight: "600",
      color: "#888AA8",
      textTransform: "uppercase",
      letterSpacing: "0.8px",
    },
    td: {
      padding: "14px 18px",
      fontSize: "14px",
      borderTop: "1px solid #2A2A3855",
    },
    nameWrap: {
      display: "flex",
      alignItems: "center",
    },
    avatar: {
      width: "32px",
      height: "32px",
      borderRadius: "50%",
      background: "#6C63FF22",
      border: "1px solid #6C63FF44",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "11px",
      fontWeight: "600",
      color: "#9B8FFF",
      marginRight: "10px",
      flexShrink: 0,
    },
    nameText: {
      fontWeight: "500",
    },
    emailText: {
      color: "#888AA8",
      fontSize: "13px",
    },
    cityPill: {
      background: "#6C63FF22",
      color: "#9B8FFF",
      border: "1px solid #6C63FF33",
      padding: "3px 10px",
      borderRadius: "20px",
      fontSize: "12px",
      fontWeight: "500",
      display: "inline-block",
    },
    actions: {
      display: "flex",
      gap: "8px",
      justifyContent: "center",
    },
    btnEdit: {
      background: "#F59E0B18",
      color: "#F59E0B",
      border: "1px solid #F59E0B44",
      padding: "6px 14px",
      borderRadius: "8px",
      fontSize: "12px",
      fontWeight: "600",
      cursor: "pointer",
      fontFamily: "'Sora', sans-serif",
    },
    btnDel: {
      background: "#F43F5E18",
      color: "#F43F5E",
      border: "1px solid #F43F5E44",
      padding: "6px 14px",
      borderRadius: "8px",
      fontSize: "12px",
      fontWeight: "600",
      cursor: "pointer",
      fontFamily: "'Sora', sans-serif",
    },
    empty: {
      textAlign: "center",
      padding: "40px",
      color: "#888AA8",
      fontSize: "14px",
    },
    loadingWrap: {
      minHeight: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      background: "#0F0F13",
      fontFamily: "'Sora', sans-serif",
    },
    loadingText: {
      fontSize: "18px",
      fontWeight: "500",
      color: "#9B8FFF",
    },
    errorText: {
      fontSize: "16px",
      color: "#F43F5E",
    },
  };